name: Build
on: [push, pull_request]
jobs:
  conda-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Build
        shell: bash -l {0}
        run: |
          conda env update -f environment.yml
          conda activate notebooks
          conda install -y ipython nbconvert nbformat
          python t_notebook.py

